- created a third_party directory... going to be renamed lib - removed slime/swank (will rely on quicklisp for that) - created a legacy directory where the older scheme implementation lives for reference - creating the plant binary as bin/plant now - moved setup.lisp to runtime/ and future support files will go there as well - simplified a bunch of things thanks to uiop - updated LICENSE and README.md - updated .gitignore - removed any automatic loading of swank - removed chunks of the shell wrapper that tested whether plant has been built. Much easier to follow now. - improved some error messages (requesting participation in the github project) - the bootstrapping is nearly satisfying now

diff --git a/plant b/plant
--- a/plant
+++ b/plant
@@ -19,9 +19,8 @@ if [ -z "$PLANT_HOME" ]; then
     export PLANT_HOME=`dirname $plant_path`
 fi
 
-export PLANT_BIN=${PLANT_HOME}/plant-bin
+PLANT_BIN=${PLANT_HOME}/bin/plant
 
-PLANT_BUILT=1
 if [ ! -x ${PLANT_BIN} ]; then
     echo "Looks like this is the first time you're running plant."
     echo "I'm going to try and build it with either clisp, sbcl, or ccl."
@@ -33,32 +32,24 @@ if [ ! -x ${PLANT_BIN} ]; then
     if [ -x `which clisp` ]; then
         echo "Building plant with clisp"
         clisp -q \
-            -x '(load "${PLANT_HOME}/asdf.lisp") (load "${PLANT_HOME}/build_plant.lisp")' \
-            -- ${PLANT_BIN}
+            -x "(load \"${PLANT_HOME}/third_party/asdf.lisp\") (load \"${PLANT_HOME}/build_plant.lisp\")"
     elif [ -x `which sbcl` ]; then
         echo "Building plant with sbcl"
         sbcl --noinform \
             --load ${PLANT_HOME}/asdf.lisp \
-            --script ${PLANT_HOME}/build_plant.lisp \
-            ${PLANT_BIN}
+            --script ${PLANT_HOME}/build_plant.lisp
     fi
     
-    if [ -x ${PLANT_BIN} ]; then
-        PLANT_BUILT=0
+    if [ ! -x ${PLANT_BIN} ]; then
+        echo "Unable to build plant. :("
+        echo "Please consider providing any terminal output in a github issue."
+        exit 1
     fi
-else
-    PLANT_BUILT=0
-fi
-
-if [ ! ${PLANT_BUILT} ]; then
-    echo "Unable to build plant. :("
-    echo "Please consider providing any terminal output in a github issue."
-    exit 1
 fi
 
 if [ -x `which ${PLANT_LISP}` ]; then
     ${PLANT_BIN} -- $@
 else
-    echo "plant currently only supports clisp, sbcl, and clozure-cl."
+    echo "I wasn't able to find a supported lisp. Please create a github issue to request support for your preferred environment. :)"
     exit 1
 fi
